name: S3 Deploy

on:
  push:
    branches:
      - 'main'

jobs:
  release-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install Dependencies
        run: npm ci
      - name: Check Memory
        run: free -m
      - name: Build App
        run: npm run build
      # - name: Run Tests
      #   run: npm test
      - name: Generate Changelog
        uses: scottbrenner/generate-changelog-action@master
        id: generate_changelog
        env:
          REPO: ${{ github.repository }}
      # name: Update package.json
      #   uses: some/action
      - name: List Files
        run: ls ${{ github.workspace }}
      - name: Bump Version and Push Tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          # dry_run: true
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.tag_version.outputs.new_tag }}
          release_name: Release ${{ steps.tag_version.outputs.new_tag }}
          body: ${{ steps.generate_changelog.outputs.changelog }}
      - name: Push to S3
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl public-read --follow-symlinks --delete
        env:
          AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: 'us-east-2' # optional: defaults to us-east-1
          SOURCE_DIR: 'dist' # optional: defaults to entire repository
